version: '3'
services:
  type-a-service:
    image: type-a-service
    ports:
      - "8081:8081"
    environment:
      - OUTBOUND_HOST_PORT=service-b:8082
      - JAEGER_SERVICE_NAME=type-a-service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
  type-b-service-0:
    image: type-b-service
    environment:
      - JAEGER_SERVICE_NAME=type-b-service-0
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
      - INSTANCE_NO=0
  type-b-service-1:
    image: type-b-service
    environment:
      - JAEGER_SERVICE_NAME=type-b-service-1
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true    
      - INSTANCE_NO=1  
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
  ubuntu:
    image: ubuntu
    command: sleep infinity
